# Generated by Django 5.1.15 on 2026-06-02 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("workout_reminder", "Recordatorio de entrenamiento"),
                            ("body_progress", "Recordatorio de progreso corporal"),
                            ("weekly_summary", "Resumen semanal"),
                            ("inactivity", "Motivación por inactividad"),
                            ("achievement", "Logro o PR"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("skipped", "Omitido"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("dedup_key", models.CharField(blank=True, max_length=64)),
                (
                    "device_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notifications.devicetoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserNotificationPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("all_enabled", models.BooleanField(default=True)),
                ("workout_enabled", models.BooleanField(default=True)),
                ("workout_days", models.JSONField(default=list)),
                ("workout_hour", models.PositiveSmallIntegerField(default=9)),
                ("workout_minute", models.PositiveSmallIntegerField(default=0)),
                ("body_progress_enabled", models.BooleanField(default=True)),
                (
                    "body_progress_frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("biweekly", "Quincenal"),
                            ("monthly", "Mensual"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "body_progress_day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        default=0,
                    ),
                ),
                ("body_progress_hour", models.PositiveSmallIntegerField(default=10)),
                ("body_progress_minute", models.PositiveSmallIntegerField(default=0)),
                ("weekly_summary_enabled", models.BooleanField(default=True)),
                (
                    "weekly_summary_day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        default=6,
                    ),
                ),
                ("weekly_summary_hour", models.PositiveSmallIntegerField(default=20)),
                ("weekly_summary_minute", models.PositiveSmallIntegerField(default=0)),
                ("inactivity_enabled", models.BooleanField(default=True)),
                (
                    "inactivity_threshold_days",
                    models.PositiveSmallIntegerField(default=3),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preferences",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "is_active"], name="notificatio_user_id_f0e72c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["user", "notification_type", "dedup_key"],
                name="notificatio_user_id_38e9ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["sent_at"], name="notificatio_sent_at_d19621_idx"
            ),
        ),
    ]
