# Generated by Django 6.0.3 on 2026-04-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.FloatField(
                blank=True, help_text="Current weight in kg", null=True
            ),
        ),
    ]
