# Generated by Django 6.0.3 on 2026-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_profile_picture_user_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="track_rpe",
            field=models.BooleanField(
                default=False, help_text="User preference to track RPE"
            ),
        ),
    ]
