# Generated by Django 6.0.3 on 2026-05-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_bodymeasures_lateral_measurements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bodymeasures",
            new_name="users_bodym_user_id_bd24b4_idx",
            old_name="users_bodym_user_id_8a0f0d_idx",
        ),
        migrations.AlterField(
            model_name="bodymeasures",
            name="weight",
            field=models.FloatField(help_text="Weight in kg"),
        ),
    ]
