# Generated by Django 6.0.3 on 2026-05-22 19:45

import apps.users.upload_paths
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0009_rename_users_bodym_user_id_8a0f0d_idx_users_bodym_user_id_bd24b4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodymeasures",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=apps.users.upload_paths.body_measure_photo_path,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=apps.users.upload_paths.profile_picture_path,
            ),
        ),
    ]
