# Generated by Django 6.0.3 on 2026-05-22 20:54

import apps.users.storage.supabase_storage
import apps.users.upload_paths
import django.db.models.deletion
from django.db import migrations, models


def copy_single_photos_to_related(apps, schema_editor):
    BodyMeasures = apps.get_model("users", "BodyMeasures")
    BodyMeasurePhoto = apps.get_model("users", "BodyMeasurePhoto")
    for measure in BodyMeasures.objects.all():
        old_photo = measure.photo
        if not old_photo or not old_photo.name:
            continue
        row = BodyMeasurePhoto(body_measure=measure, order=0)
        row.image.save(old_photo.name, old_photo, save=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_supabase_storage_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyMeasurePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=apps.users.storage.supabase_storage.SupabaseBodyStorage(),
                        upload_to=apps.users.upload_paths.body_measure_photo_path,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "body_measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_photos",
                        to="users.bodymeasures",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(copy_single_photos_to_related, noop_reverse),
        migrations.RemoveField(
            model_name="bodymeasures",
            name="photo",
        ),
    ]
