# Generated by Django 6.0.3 on 2026-05-22 20:59

import apps.users.storage.supabase_storage
import apps.users.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_body_measure_multiple_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.users.storage.supabase_storage.SupabaseProfileStorage(),
                upload_to=apps.users.upload_paths.profile_picture_path,
            ),
        ),
    ]
