# Generated by Django 6.0.3 on 2026-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineexercise",
            name="rest_time_seconds",
            field=models.IntegerField(default=60),
        ),
    ]
