# Generated by Django 6.0.2 on 2026-03-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('muscle_group', models.CharField(choices=[('chest', 'Pectoral'), ('back', 'Dorsal'), ('shoulders', 'Hombros'), ('quadriceps', 'Cuádriceps'), ('hamstrings', 'Isquiotibiales (Femorales)'), ('calves', 'Gemelos'), ('glutes', 'Glúteos'), ('adductors', 'Adductores'), ('abductors', 'Abductores'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('forearms', 'Antebrazos'), ('abs', 'Abdominales'), ('others', 'Otros')], max_length=50)),
                ('equipment', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise_type', models.CharField(choices=[('barbell', 'Barra'), ('dumbbell', 'Mancuernas'), ('machine', 'Máquina'), ('cable', 'Polea'), ('bodyweight', 'Peso Corporal'), ('kettlebell', 'Pesa Rusa'), ('smith_machine', 'Máquina Smith'), ('other', 'Otro')], default='weight_reps', max_length=20)),
                ('is_global', models.BooleanField(default=False, help_text='True si es un ejercicio de la app')),
            ],
        ),
    ]
