# Generated by Django 6.0.3 on 2026-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="gif_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="instructions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de pasos para realizar el ejercicio",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="equipment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("barbell", "Barra"),
                    ("dumbbell", "Mancuernas"),
                    ("machine", "Máquina"),
                    ("cable", "Polea"),
                    ("bodyweight", "Peso Corporal"),
                    ("kettlebell", "Pesa Rusa"),
                    ("smith_machine", "Máquina Smith"),
                    ("other", "Otro"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
