# Generated by Django 6.0.3 on 2026-04-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_exercise_description_exercise_gif_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("chest", "Pecho"),
                    ("back", "Espalda"),
                    ("shoulders", "Hombros"),
                    ("traps", "Trapecios"),
                    ("quadriceps", "Cuádriceps"),
                    ("hamstrings", "Isquiotibiales"),
                    ("calves", "Gemelos"),
                    ("glutes", "Glúteos"),
                    ("adductors", "Aductores"),
                    ("abductors", "Abductores"),
                    ("biceps", "Bíceps"),
                    ("triceps", "Tríceps"),
                    ("forearms", "Antebrazos"),
                    ("abs", "Abdominales"),
                    ("lower_back", "Espalda Baja"),
                    ("cardio", "Cardio"),
                    ("others", "Otros"),
                ],
                max_length=50,
            ),
        ),
    ]
