# Generated by Django 6.0.3 on 2026-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0004_alter_exercise_muscle_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="ID original de ExerciseDB",
                max_length=20,
                null=True,
            ),
        ),
    ]
