# Generated by Django 6.0.3 on 2026-04-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0005_exercise_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("barra", "Barra"),
                    ("mancuernas", "Mancuernas"),
                    ("maquina", "Máquina"),
                    ("polea", "Polea"),
                    ("peso_corporal", "Peso Corporal"),
                    ("pesa_rusa", "Pesa Rusa"),
                    ("maquina_smith", "Máquina Smith"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(
                choices=[
                    ("pecho", "Pecho"),
                    ("espalda", "Espalda"),
                    ("hombros", "Hombros"),
                    ("trapecios", "Trapecios"),
                    ("cuadriceps", "Cuádriceps"),
                    ("isquiotibiales", "Isquiotibiales"),
                    ("gemelos", "Gemelos"),
                    ("gluteos", "Glúteos"),
                    ("aductores", "Aductores"),
                    ("abductores", "Abductores"),
                    ("biceps", "Bíceps"),
                    ("triceps", "Tríceps"),
                    ("antebrazos", "Antebrazos"),
                    ("abdominales", "Abdominales"),
                    ("espalda_baja", "Espalda Baja"),
                    ("cardio", "Cardio"),
                    ("otros", "Otros"),
                ],
                max_length=50,
            ),
        ),
    ]
