# Generated by Django 6.0.3 on 2026-04-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0006_alter_exercise_exercise_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("barra", "Barra"),
                    ("mancuernas", "Mancuernas"),
                    ("maquina", "Máquina"),
                    ("polea", "Polea"),
                    ("peso_corporal", "Peso Corporal"),
                    ("pesa_rusa", "Pesa Rusa"),
                    ("maquina_smith", "Máquina Smith"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="ID original de ExerciseDB",
                max_length=100,
                null=True,
            ),
        ),
    ]
