# Generated by Django 6.0.3 on 2026-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0008_alter_exercise_exercise_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="difficulty",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="secondary_muscles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de otros músculos involucrados",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="target",
            field=models.CharField(
                blank=True,
                help_text="Músculo objetivo específico",
                max_length=100,
                null=True,
            ),
        ),
    ]
