# Generated by Django 6.0.3 on 2026-06-08 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Fuerza"),
                            ("consistency", "Constancia"),
                            ("volume", "Volumen"),
                            ("records", "Récords"),
                            ("body_progress", "Progreso corporal"),
                            ("routines", "Rutinas"),
                            ("profile", "Perfil"),
                            ("special", "Especiales"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bronze", "Bronce"),
                            ("silver", "Plata"),
                            ("gold", "Oro"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("subtitle", models.CharField(max_length=80)),
                ("description", models.TextField()),
                (
                    "icon_key",
                    models.CharField(
                        help_text="Clave para mapear al icono Material en el frontend.",
                        max_length=64,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Ilustración del logro (opcional).",
                        null=True,
                        upload_to="achievements/",
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Parámetros para evaluar el logro (tipo, umbrales, etc.).",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_unlocked", models.BooleanField(default=False)),
                ("progress", models.FloatField(default=0.0)),
                ("progress_label", models.CharField(blank=True, max_length=80)),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_records",
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_unlocked"],
                        name="achievement_user_id_1c4002_idx",
                    )
                ],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
