# Generated by Django 6.0.3 on 2026-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workouts",
            "0002_workoutsession_end_time_workoutsession_is_completed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutset",
            name="rpe",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutset",
            name="set_type",
            field=models.CharField(default="normal", max_length=20),
        ),
    ]
