# Generated by Django 6.0.3 on 2026-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_workoutset_rpe_workoutset_set_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutset",
            name="rir",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
