# Generated by Django 6.0.3 on 2026-05-05 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_workoutset_rir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutsession",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
