import 'package:flutter/material.dart';

/// Mapeo de icon_key (BD) → IconData Material.
IconData achievementIconFor(String key) {
  return _icons[key] ?? Icons.emoji_events;
}

const _icons = <String, IconData>{
  'fitness_center': Icons.fitness_center,
  'accessibility_new': Icons.accessibility_new,
  'vertical_align_bottom': Icons.vertical_align_bottom,
  'trending_up': Icons.trending_up,
  'arrow_upward': Icons.arrow_upward,
  'swap_vert': Icons.swap_vert,
  'open_in_full': Icons.open_in_full,
  'format_align_left': Icons.format_align_left,
  'compress': Icons.compress,
  'arrow_downward': Icons.arrow_downward,
  'table_rows': Icons.table_rows,
  'self_improvement': Icons.self_improvement,
  'south': Icons.south,
  'flag': Icons.flag,
  'local_fire_department': Icons.local_fire_department,
  'whatshot': Icons.whatshot,
  'bolt': Icons.bolt,
  'calendar_month': Icons.calendar_month,
  'event_available': Icons.event_available,
  'cake': Icons.cake,
  'sports_gymnastics': Icons.sports_gymnastics,
  'military_tech': Icons.military_tech,
  'shield': Icons.shield,
  'repeat': Icons.repeat,
  'autorenew': Icons.autorenew,
  'scale': Icons.scale,
  'timer': Icons.timer,
  'leaderboard': Icons.leaderboard,
  'emoji_events': Icons.emoji_events,
  'show_chart': Icons.show_chart,
  'straighten': Icons.straighten,
  'monitor_weight_outlined': Icons.monitor_weight_outlined,
  'photo_camera': Icons.photo_camera,
  'collections': Icons.collections,
  'playlist_add': Icons.playlist_add,
  'view_list': Icons.view_list,
  'explore': Icons.explore,
  'hub': Icons.hub,
  'lightbulb_outline': Icons.lightbulb_outline,
  'check_circle_outline': Icons.check_circle_outline,
  'account_circle': Icons.account_circle,
  'nightlight_round': Icons.nightlight_round,
  'wb_sunny_outlined': Icons.wb_sunny_outlined,
  'weekend': Icons.weekend,
  'accessibility': Icons.accessibility,
  'analytics_outlined': Icons.analytics_outlined,
  'replay': Icons.replay,
};
